### ISSUE TITLE
null is not an object (evaluating 'RNZxcvbn.score')

### ISSUE THREAD

**Issue by floriaaan** [doomsower/react-native-zxcvbn#3]
Using score(password) returns null :/

Here's a little bit of my ReactNative Register Page code.

``` js
import { score } from "react-native-zxcvbn";
const handlePass = async (text) => {
    if (text !== "") {
      const passformat = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/;
      passformat.test(text) ? setPasswordValid(true) : setPasswordValid(false);
      let _score = await score(text); // There, _score is null.
   }
}
```

**Comment by doomsower** [comment]
Is it iOS/Android? Does example app work for you?

**Comment by floriaaan** [comment]
It is Android, I haven't tried example app because I'm using Expo not React-Native CLI in my project, but is Expo unsupported ?

**Comment by doomsower** [comment]
Last time I checked expo didn't support arbitrary native modules like this one.

**Comment by floriaaan** [comment]
Oh :(

Okay, Expo sucks at this point because I mean to use zxcvbn regularly in my projects, and that's the first time making react native ones, and I know the work in making a web script usable in native apps.

Have you planned to make Expo compatible ?

**Comment by doomsower** [comment]
I think they hand-pick packages, and there's no way such small and specialized package would make it. This is the point of Expo - it's just RN + some stuff that 80% of apps use.

**Comment by doomsower** [comment]
You can still use js-side zxcvbn with expo. I used js module before I wrote this. Native zxcvbn does add very small performance improvement.

**Comment by ab-sami** [comment]
This issue still exists on react-native-cli as well. Can we please get a fix for this.

**Comment by hirbod** [comment]
This package can be used with Expo now (using an expo custom-dev-client)
